const SB_URL='https://rokitvbpvjzkjboqofpk.supabase.co',SB_KEY='sb_publishable_M4q-bqB3ETJKoU9lfIj4dQ_UgCeL6z-';
const sb=supabase.createClient(SB_URL,SB_KEY),$=id=>document.getElementById(id),sections=['home','lobby','answer','vote','results','scores','finalVote','winner'];
let session=JSON.parse(localStorage.getItem('striplash_session_v15')||'null'),snap=null,currentScreen='home',submittedKey='',votedMatch='',lastPromptKey='',nameRevealShown=false,finalVoted=false,winnerShown=false;
function show(id){sections.forEach(x=>$(x).classList.toggle('hidden',x!==id));if(currentScreen!==id){currentScreen=id;scrollTo(0,0)}}
function toast(t){$('toast').textContent=t;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),2200)}
function save(){localStorage.setItem('striplash_session_v15',JSON.stringify(session))}function leave(msg){localStorage.removeItem('striplash_session_v15');session=null;snap=null;submittedKey='';votedMatch='';lastPromptKey='';nameRevealShown=false;finalVoted=false;winnerShown=false;show('home');if(msg)toast(msg)}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}async function rpc(fn,args){const {data,error}=await sb.rpc(fn,args);if(error)throw error;return data}
function norm(s){return String(s).toLowerCase().normalize('NFKD').replace(/[0@]/g,'o').replace(/[1!|]/g,'i').replace(/3/g,'e').replace(/4/g,'a').replace(/5|\$/g,'s').replace(/7/g,'t').replace(/[^a-z0-9 ]/g,' ').replace(/\s+/g,' ').trim()}
function hits(t,a){return a.reduce((n,w)=>n+(t.includes(w)?1:0),0)}
function hateAnalyze(text){const t=norm(text);let racism=0,sexism=0,antisemitism=0,antiLgbtq=0;const racial=['nigger','nigga','chink','gook','spic','wetback','coon','raghead'],sexist=['femoid','dishwasher','slut','whore'],anti=['kike','heeb','jewboy','jewess','yid'],lgbt=['fag','faggot','dyke','tranny'];racism=Math.min(100,hits(t,racial)*95);sexism=Math.min(100,hits(t,sexist)*80);antisemitism=Math.min(100,hits(t,anti)*95);antiLgbtq=Math.min(100,hits(t,lgbt)*95);if(/\b(jew|jews|jewish|rabbi)\b/.test(t)&&/(fuck|hate|kill|burn|dirty|evil|vermin|rat|greedy|cheap|money|bank|media|control|oven|gas|auschwitz|holocaust)/.test(t))antisemitism=Math.max(antisemitism,92);if(/\b(gay|gays|lesbian|trans|transgender)\b/.test(t)&&/(fuck|hate|kill|dirty|evil|inferior|disgusting)/.test(t))antiLgbtq=Math.max(antiLgbtq,88);if(/women|woman|girls|girl/.test(t)&&/(stupid|dumb|worthless|inferior|kitchen|property)/.test(t))sexism=Math.max(sexism,68);return{racism,sexism,antisemitism,antiLgbtq,targetedHate:Math.max(racism,sexism,antisemitism,antiLgbtq)}}
function nameAnalyze(name){const t=norm(name),hate=hateAnalyze(name);let s=hits(t,['fuck','shit','dick','cock','pussy','tits','cum','ass'])*18+hits(t,['daddy','mommy','hard','wet','strip','naked','booty','horny','shaft','ride','bang','suck','blow'])*11+(/69|xxx|420/.test(t)?12:0);s=Math.min(100,s);return{score:s,bonus:Math.min(200,Math.round(s*2)),...hate}}
function analyze(answer,prompt){const raw=String(answer),t=norm(raw),p=norm(prompt),hate=hateAnalyze(raw);let sexual=Math.min(100,hits(t,['sex','cock','dick','pussy','anus','butt','boner','cum','semen','oral','blowjob','handjob','naked','orgasm','fetish','fist','rimjob','69'])*28);let dark=Math.min(100,hits(t,['corpse','dead','body','grave','funeral','morgue','murder','kill','necroph','cadaver','suicide'])*26);let gross=Math.min(100,hits(t,['shit','poop','piss','vomit','diarrhea','blood','rectum','fart','pus','mucus'])*25);let profanity=Math.min(100,hits(t,['fuck','shit','bitch','asshole','motherfucker','damn','cunt'])*22),context=0;if(p.includes('prostate')&&/(arm|elbow|fist|shoulder|whole hand|both hands|wrist)/.test(t)){context=92;sexual=Math.max(sexual,72)}if((p.includes('funeral')||p.includes('morgue'))&&/(body|corpse|dead)/.test(t)&&/(use|clean|bed|sex|ride|touch|stiff)/.test(t)){context=96;dark=Math.max(dark,92);sexual=Math.max(sexual,70)}if(/necroph/.test(t)){context=100;dark=100;sexual=Math.max(sexual,80)}let boring=raw.trim().length<8?100:raw.trim().length<15?50:0;if(['idk','nothing','whatever','lol','no idea','poop','sex','your mom','ur mom'].includes(raw.trim().toLowerCase()))boring+=150;let score=Math.min(100,Math.round(8+sexual*.42+dark*.19+gross*.13+profanity*.12+context*.32)),bonus=Math.round(score*2);return{score,bonus,sexual,dark,gross,profanity,context,boring_penalty:Math.min(300,boring),...hate}}
function metric(l,v){return `<div class="metric"><span>${l}</span><div class="track"><div class="fill" style="width:${v}%"></div></div><b>${v}</b></div>`}
function showRef(title,sub){const d=document.createElement('div');d.className='overlay';d.innerHTML=`<div class="overlayBox"><div class="refMascot">🧑‍⚖️</div><h2>${title}</h2><p>${sub}</p></div>`;document.body.appendChild(d);setTimeout(()=>d.remove(),1650)}
function renderAnalysis(a){$('analysisBox').classList.remove('hidden');$('analysisBox').innerHTML=`<h3>DEGENERACY ANALYSIS</h3><div class="analysisScore">${a.score}</div><div class="small">OUT OF 100 · BONUS <b class="bonus">+${a.bonus}</b>${a.boring_penalty?` · BORING RISK <b style="color:var(--red)">-${a.boring_penalty}</b>`:''}</div>${metric('Sexual',a.sexual)}${metric('Dark',a.dark)}${metric('Gross-out',a.gross)}${metric('Profanity',a.profanity)}${metric('Context',a.context)}${metric('Racism',a.racism)}${metric('Sexism',a.sexism)}${metric('Antisemitism',a.antisemitism)}${metric('Anti-LGBTQ',a.antiLgbtq)}<p class="small">Protected-group meters are detected separately and do not directly add bonus points.</p>`;if(a.antisemitism>=35)showRef('ANTISEMITISM DETECTED','OY VEY!');else if(a.antiLgbtq>=35)showRef('ANTI-LGBTQ CONTENT DETECTED','TARGETED HATE FLAGGED')}
function nameReveal(me){if(nameRevealShown)return;nameRevealShown=true;const off=(session.nameAnalysis?.targetedHate||0)>0,d=document.createElement('div');d.className='overlay';d.innerHTML=`<div class="overlayBox"><div class="small">YOUR ONE-TIME NAME BONUS</div><div class="big">+${me.name_bonus}</div><h2>${off?'OFFENSIVE NAME':me.name_bonus?'RAUNCHY NAME!':'CLEAN NAME'}</h2><p>${esc(me.name)}</p><button id="closeName">LET'S GO</button></div>`;document.body.appendChild(d);d.querySelector('#closeName').onclick=()=>d.remove();setTimeout(()=>{if(d.isConnected)d.remove()},4000)}
async function createRoom(){const name=$('nick').value.trim();if(!name)return toast('Enter a nickname first.');const a=nameAnalyze(name);try{const d=await rpc('create_room',{p_name:name,p_name_raunch:a.score,p_name_bonus:a.bonus});session={...d,name,isHost:true,nameAnalysis:a};save();refresh(true)}catch(e){toast(e.message)}}
async function joinRoom(){const name=$('nick').value.trim(),code=$('joinCode').value.trim().toUpperCase();if(!name||code.length!==4)return toast('Enter a nickname and 4-character room code.');const a=nameAnalyze(name);try{const d=await rpc('join_room',{p_code:code,p_name:name,p_name_raunch:a.score,p_name_bonus:a.bonus});session={...d,name,isHost:false,nameAnalysis:a};save();refresh(true)}catch(e){toast(e.message)}}
async function refresh(force=false){if(!session)return;try{snap=await rpc('room_snapshot',{p_code:session.code});if(!snap?.room){leave('Game ended.');return}render()}catch(e){if(force)toast(e.message)}}
function prepPrompt(r){const k=`${r.round_no}-${r.prompt_index}-${r.prompt_text}`;if(k!==lastPromptKey){lastPromptKey=k;submittedKey='';votedMatch='';finalVoted=false;$('answerText').value='';$('analysisBox').classList.add('hidden');$('analysisBox').innerHTML=''}}
function render(){const r=snap.room,players=snap.players||[],me=players.find(x=>x.id===session.player_id);$('roomCode').textContent=r.code;document.querySelectorAll('.restart').forEach(b=>b.classList.toggle('hidden',!session.isHost));$('players').innerHTML=players.map(p=>`<div class="player"><span>${esc(p.name)} ${p.id===session.player_id?'(you)':''}</span><span class="small">READY</span></div>`).join('');if(r.status==='lobby'){show('lobby');$('lobbyStatus').textContent=`${players.length} player${players.length===1?'':'s'} joined.`;$('startBtn').classList.toggle('hidden',!session.isHost)}else if(r.status==='answering'||r.status==='final_answering'){show('answer');if(me)nameReveal(me);prepPrompt(r);$('roundLabel').innerHTML=r.status==='final_answering'?'<span class="finalTag">FINAL STRIPLASH · EVERYONE ANSWERS</span>':`ROUND ${r.round_no} · PROMPT ${r.prompt_index}/3`;$('prompt').textContent=r.prompt_text;const key=r.round_no+'-'+r.prompt_index,locked=key===submittedKey;$('answerText').disabled=locked;$('submitBtn').disabled=locked;$('answerStatus').textContent=locked?`Locked in. ${snap.submitted}/${players.length} answers submitted.`:`${snap.submitted}/${players.length} answers submitted.`;$('votingBtn').textContent=r.status==='final_answering'?'HOST: START FINAL VOTING':'HOST: START VOTING';$('votingBtn').classList.toggle('hidden',!(session.isHost&&snap.submitted>=2))}else if(r.status==='voting'){show('vote');$('votePrompt').textContent=r.prompt_text;loadMatchup()}else if(r.status==='results'){show('results');$('nextMatchBtn').classList.toggle('hidden',!session.isHost);$('waitNext').classList.toggle('hidden',session.isHost)}else if(r.status==='scores'){show('scores');const sorted=[...players].sort((a,b)=>b.score-a.score);$('leaderboard').innerHTML=sorted.map((p,i)=>`<div class="player"><span>${i+1}. <b>${esc(p.name)}</b></span><span><b>${p.score}</b> pts</span></div>`).join('');const finalReady=r.round_no===2&&r.prompt_index===3;$('nextPromptBtn').classList.toggle('hidden',!session.isHost||finalReady);$('startFinalBtn').classList.toggle('hidden',!session.isHost||!finalReady);$('scoreHeading').textContent=finalReady?'Round 2 Complete':'Leaderboard'}else if(r.status==='final_voting'){show('finalVote');loadFinal()}else if(r.status==='finished'){showWinner(players)}}
async function startGame(){try{await rpc('start_game',{p_room_id:session.room_id,p_host_token:session.host_token});nameRevealShown=false;refresh(true)}catch(e){toast(e.message)}}
async function submitAnswer(){const ans=$('answerText').value.trim();if(!ans)return toast('Type an answer first.');const a=analyze(ans,snap.room.prompt_text);try{await rpc('submit_answer',{p_room_id:session.room_id,p_player_id:session.player_id,p_player_token:session.player_token,p_answer:ans,p_raunch:a.score,p_bonus:a.bonus,p_analysis:a});submittedKey=snap.room.round_no+'-'+snap.room.prompt_index;renderAnalysis(a);$('answerText').disabled=true;$('submitBtn').disabled=true;refresh(true)}catch(e){toast(e.message)}}
async function prepareVoting(){try{const fn=snap.room.status==='final_answering'?'prepare_final_voting':'prepare_voting';await rpc(fn,{p_room_id:session.room_id,p_host_token:session.host_token});refresh(true)}catch(e){toast(e.message)}}
async function loadMatchup(){try{const m=await rpc('active_matchup_snapshot',{p_code:session.code});if(!m)return;$('matchup').innerHTML=`<div class="answer">A: “${esc(m.a_answer)}”<button onclick="castVote('${m.matchup_id}','${m.a_id}')">VOTE A</button></div><div class="answer">B: “${esc(m.b_answer)}”<button onclick="castVote('${m.matchup_id}','${m.b_id}')">VOTE B</button></div>`;const v=+m.votes||0,e=+m.eligible_voters||0;$('voteStatus').innerHTML=session.isHost?`<b>${v}/${e}</b> players have voted.${e&&v>=e?' <b style="color:var(--green)">EVERYONE HAS VOTED ✓</b>':''}`:(votedMatch===m.matchup_id?'Vote locked in.':'Waiting for votes...');$('scoreBtn').classList.toggle('hidden',!session.isHost);$('scoreBtn').disabled=session.isHost&&e>0&&v<e}catch(e){toast(e.message)}}
window.castVote=async(mid,sid)=>{try{await rpc('cast_vote',{p_matchup_id:mid,p_player_id:session.player_id,p_player_token:session.player_token,p_submission_id:sid});votedMatch=mid;loadMatchup()}catch(e){toast(e.message)}}
async function scoreMatch(){try{await rpc('score_current_matchup',{p_room_id:session.room_id,p_host_token:session.host_token});refresh(true)}catch(e){toast(e.message)}}
async function nextMatch(){try{await rpc('next_matchup',{p_room_id:session.room_id,p_host_token:session.host_token});votedMatch='';refresh(true)}catch(e){toast(e.message)}}
async function nextPrompt(){try{await rpc('next_prompt',{p_room_id:session.room_id,p_host_token:session.host_token});refresh(true)}catch(e){toast(e.message)}}
async function startFinal(){try{await rpc('start_final_round',{p_room_id:session.room_id,p_host_token:session.host_token});refresh(true)}catch(e){toast(e.message)}}
async function loadFinal(){try{const f=await rpc('final_round_snapshot',{p_code:session.code});$('finalPrompt').textContent=f.room.prompt_text;const answers=f.answers||[];$('finalAnswers').innerHTML=answers.map((a,i)=>`<div class="answer">${i+1}. “${esc(a.answer)}”${a.player_id===session.player_id?'<div class="small">YOUR ANSWER</div>':`<button onclick="castFinal('${a.submission_id}')">VOTE FOR THIS</button>`}</div>`).join('');const v=+f.votes_cast||0,e=+f.eligible_voters||0;$('finalVoteStatus').innerHTML=session.isHost?`<b>${v}/${e}</b> players have voted.${e&&v>=e?' <b style="color:var(--green)">EVERYONE HAS VOTED ✓</b>':''}`:(finalVoted?'Final vote locked in.':'Choose your favorite answer.');$('scoreFinalBtn').classList.toggle('hidden',!session.isHost);$('scoreFinalBtn').disabled=session.isHost&&v<e}catch(e){toast(e.message)}}
window.castFinal=async sid=>{try{await rpc('cast_final_vote',{p_room_id:session.room_id,p_player_id:session.player_id,p_player_token:session.player_token,p_submission_id:sid});finalVoted=true;toast('Final vote locked in');loadFinal()}catch(e){toast(e.message)}}
async function scoreFinal(){try{await rpc('score_final_round',{p_room_id:session.room_id,p_host_token:session.host_token});refresh(true)}catch(e){toast(e.message)}}
function confetti(){for(let i=0;i<70;i++){const d=document.createElement('i');d.className='confetti';d.style.left=Math.random()*100+'vw';d.style.animationDelay=Math.random()*1.2+'s';d.style.background=`hsl(${Math.random()*360} 90% 60%)`;document.body.appendChild(d);setTimeout(()=>d.remove(),4700)}}
function showWinner(players){show('winner');const sorted=[...players].sort((a,b)=>b.score-a.score),w=sorted[0];$('winnerName').textContent=w?.name||'Winner';$('winnerScore').textContent=(w?.score||0)+' PTS';$('finalLeaderboard').innerHTML=sorted.map((p,i)=>`<div class="player"><span>${i+1}. <b>${esc(p.name)}</b></span><b>${p.score}</b></div>`).join('');document.querySelector('#winner .restart').classList.toggle('hidden',!session.isHost);if(!winnerShown){winnerShown=true;confetti()}}
async function restartGame(){if(!session?.isHost)return;if(!confirm('Restart the game? Everyone will be kicked back to the main screen.'))return;try{await rpc('restart_game',{p_room_id:session.room_id,p_host_token:session.host_token});leave('Game restarted.')}catch(e){toast(e.message)}}
$('createBtn').onclick=createRoom;$('joinBtn').onclick=joinRoom;$('leaveBtn').onclick=()=>leave();$('startBtn').onclick=startGame;$('submitBtn').onclick=submitAnswer;$('votingBtn').onclick=prepareVoting;$('scoreBtn').onclick=scoreMatch;$('nextMatchBtn').onclick=nextMatch;$('nextPromptBtn').onclick=nextPrompt;$('startFinalBtn').onclick=startFinal;$('scoreFinalBtn').onclick=scoreFinal;document.querySelectorAll('.restart').forEach(b=>b.onclick=restartGame);if(session){$('nick').value=session.name||'';refresh(true)}else show('home');setInterval(()=>{if(session)refresh(false)},1000);