const SB_URL='https://rokitvbpvjzkjboqofpk.supabase.co',SB_KEY='sb_publishable_M4q-bqB3ETJKoU9lfIj4dQ_UgCeL6z-';
const sb=supabase.createClient(SB_URL,SB_KEY),$=id=>document.getElementById(id),sections=['home','lobby','answer','vote','results','scores','finalVote','winner'];
let session=JSON.parse(localStorage.getItem('striplash_session_v16')||'null'),snap=null,currentScreen='home',submittedKey='',votedMatch='',lastPromptKey='',nameRevealShown=false,finalVoted=false,winnerShown=false,answerMode='text',drawingDirty=false,drawHistory=[],drawing=false,autoSubmitting=false,hydrateKey='',roastShownKey='',serverBase=Date.now(),perfBase=performance.now();
const canvas=$('drawCanvas'),ctx=canvas.getContext('2d',{alpha:false});
function resetCanvas(){ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.strokeStyle='#111';ctx.lineWidth=8;ctx.lineCap='round';ctx.lineJoin='round';drawingDirty=false;drawHistory=[]}
resetCanvas();
function show(id){sections.forEach(x=>$(x).classList.toggle('hidden',x!==id));if(currentScreen!==id){currentScreen=id;scrollTo(0,0)}}
function toast(t){$('toast').textContent=t;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),2200)}
function save(){localStorage.setItem('striplash_session_v16',JSON.stringify(session))}
function leave(msg){localStorage.removeItem('striplash_session_v16');session=null;snap=null;submittedKey='';votedMatch='';lastPromptKey='';nameRevealShown=false;finalVoted=false;winnerShown=false;hydrateKey='';show('home');if(msg)toast(msg)}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
async function rpc(fn,args){const {data,error}=await sb.rpc(fn,args);if(error)throw error;return data}
function norm(s){return String(s).toLowerCase().normalize('NFKD').replace(/[0@]/g,'o').replace(/[1!|]/g,'i').replace(/3/g,'e').replace(/4/g,'a').replace(/5|\$/g,'s').replace(/7/g,'t').replace(/[^a-z0-9 ]/g,' ').replace(/\s+/g,' ').trim()}
function hits(t,a){return a.reduce((n,w)=>n+(t.includes(w)?1:0),0)}
function hateAnalyze(text){const t=norm(text);let racism=0,sexism=0,antisemitism=0,antiLgbtq=0;const racial=['nigger','nigga','chink','gook','spic','wetback','coon','raghead'],sexist=['femoid','dishwasher','slut','whore'],anti=['kike','heeb','jewboy','jewess','yid'],lgbt=['fag','faggot','dyke','tranny'];racism=Math.min(100,hits(t,racial)*95);sexism=Math.min(100,hits(t,sexist)*80);antisemitism=Math.min(100,hits(t,anti)*95);antiLgbtq=Math.min(100,hits(t,lgbt)*95);if(/\b(jew|jews|jewish|rabbi|rabbis)\b/.test(t)&&/(fuck|hate|kill|burn|dirty|evil|vermin|rat|greedy|cheap|money|bank|media|control|oven|gas|auschwitz|holocaust)/.test(t))antisemitism=Math.max(antisemitism,92);if(/\b(gay|gays|lesbian|lesbians|trans|transgender)\b/.test(t)&&/(fuck|hate|kill|dirty|evil|inferior|disgusting)/.test(t))antiLgbtq=Math.max(antiLgbtq,88);if(/women|woman|girls|girl/.test(t)&&/(stupid|dumb|worthless|inferior|kitchen|property|dishwasher)/.test(t))sexism=Math.max(sexism,68);if(/black|asian|mexican|latino|arab|indian|immigrant|white/.test(t)&&/(stupid|dumb|lazy|criminal|terrorist|steal|inferior|monkey|dirty)/.test(t))racism=Math.max(racism,70);return{racism,sexism,antisemitism,antiLgbtq,targetedHate:Math.max(racism,sexism,antisemitism,antiLgbtq)}}
function nameAnalyze(name){const t=norm(name),hate=hateAnalyze(name);let s=hits(t,['fuck','shit','dick','cock','pussy','tits','cum','ass'])*18+hits(t,['daddy','mommy','hard','wet','strip','naked','booty','horny','shaft','ride','bang','suck','blow'])*11+(/69|xxx|420/.test(t)?12:0);return{score:Math.min(100,s),...hate}}
function analyze(answer,prompt){const raw=String(answer),t=norm(raw),p=norm(prompt),hate=hateAnalyze(raw);let sexual=Math.min(100,hits(t,['sex','cock','dick','pussy','anus','butt','boner','cum','semen','oral','blowjob','handjob','naked','orgasm','fetish','fist','rimjob','69'])*28);let dark=Math.min(100,hits(t,['corpse','dead','body','grave','funeral','morgue','murder','kill','necroph','cadaver','suicide'])*26);let gross=Math.min(100,hits(t,['shit','poop','piss','vomit','diarrhea','blood','rectum','fart','pus','mucus'])*25);let profanity=Math.min(100,hits(t,['fuck','shit','bitch','asshole','motherfucker','damn','cunt'])*22),context=0;if(p.includes('prostate')&&/(arm|elbow|fist|shoulder|whole hand|both hands|wrist)/.test(t)){context=92;sexual=Math.max(sexual,72)}if((p.includes('funeral')||p.includes('morgue'))&&/(body|corpse|dead)/.test(t)&&/(use|clean|bed|sex|ride|touch|stiff)/.test(t)){context=96;dark=Math.max(dark,92);sexual=Math.max(sexual,70)}if(/necroph/.test(t)){context=100;dark=100;sexual=Math.max(sexual,80)}const score=Math.min(100,Math.round(8+sexual*.42+dark*.19+gross*.13+profanity*.12+context*.32));return{score,sexual,dark,gross,profanity,context,...hate}}
function blankAnalysis(extra={}){return{score:0,sexual:0,dark:0,gross:0,profanity:0,context:0,racism:0,sexism:0,antisemitism:0,antiLgbtq:0,targetedHate:0,...extra}}
const roasts={antisemitism:["Jesus Christ, asshole. Even the rabbi left the group chat.","Mazel tov, bastard. You made the family dinner awkward.","Easy there, asshole. That joke needs a lawyer.","DEGENERATE FOUL: you just got uninvited from the deli."],antiLgbtq:["Congrats, bastard. You made Thanksgiving awkward.","Asshole detected. The group chat has filed a complaint.","DEGENERATE FOUL: even your uncle at Thanksgiving thinks that was a lot.","Bastard behavior detected. HR has entered the chat."],racism:["Holy shit, asshole. HR would like a word.","Congratulations, bastard. You speedran sensitivity training.","DEGENERATE FOUL. Straight to HR jail.","Asshole alert: the diversity seminar just became mandatory."],sexism:["Bastard detected. Your dating-app matches just dropped by 80%.","Congrats, asshole. The group chat is now judging you.","DEGENERATE FOUL: your dating profile has been reported.","Bastard behavior detected. HR is warming up the PowerPoint."]};
function pick(a){return a[Math.floor(Math.random()*a.length)]}
function showRef(title,line){const d=document.createElement('div');d.className='overlay';d.innerHTML=`<div class="overlayBox"><div style="font-size:72px">🧑‍⚖️</div><h2>${esc(title)}</h2><p>${esc(line)}</p></div>`;document.body.appendChild(d);setTimeout(()=>d.remove(),1900)}
function maybeRoast(a,key){if(roastShownKey===key)return;let cat='',title='';if(a.antisemitism>=35){cat='antisemitism';title='ANTISEMITISM DETECTED'}else if(a.antiLgbtq>=35){cat='antiLgbtq';title='ANTI-LGBTQ CONTENT DETECTED'}else if(a.racism>=35){cat='racism';title='RACISM DETECTED'}else if(a.sexism>=35){cat='sexism';title='SEXISM DETECTED'}if(cat){roastShownKey=key;showRef(title,pick(roasts[cat]))}}
function metric(l,v){return `<div class="metric"><span>${l}</span><div class="track"><div class="fill" style="width:${v}%"></div></div><b>${v}</b></div>`}
function renderAnalysis(a,key,allowRoast=true){a=a||blankAnalysis();$('analysisBox').classList.remove('hidden');const note=a.drawing?'Drawing submitted — the chart cannot inspect the picture, so players judge it directly.':a.no_answer?'No answer submitted.':'This chart is for entertainment only. It does not award points.';$('analysisBox').innerHTML=`<h3>DEGENERACY ANALYSIS</h3><div class="analysisScore">${a.score||0}</div><div class="small">OUT OF 100 · VOTES DETERMINE YOUR SCORE</div>${metric('Sexual',a.sexual||0)}${metric('Dark',a.dark||0)}${metric('Gross-out',a.gross||0)}${metric('Profanity',a.profanity||0)}${metric('Context',a.context||0)}${metric('Racism',a.racism||0)}${metric('Sexism',a.sexism||0)}${metric('Antisemitism',a.antisemitism||0)}${metric('Anti-LGBTQ',a.antiLgbtq||0)}<p class="small">${note}</p>`;if(allowRoast)maybeRoast(a,key)}
function nameReveal(me){if(nameRevealShown)return;nameRevealShown=true;const a=session.nameAnalysis||nameAnalyze(me.name),flag=a.targetedHate>0,d=document.createElement('div');d.className='overlay';d.innerHTML=`<div class="overlayBox"><div class="small">YOUR NAME DEGENERACY</div><div class="big">${a.score}/100</div><h2>${flag?'FLAGGED NAME':a.score>=60?'FILTHY NAME':a.score?'RAUNCHY NAME':'CLEAN NAME'}</h2><p>${esc(me.name)}</p><div class="small">No name points — this is just for laughs.</div><button id="closeName">LET'S GO</button></div>`;document.body.appendChild(d);d.querySelector('#closeName').onclick=()=>d.remove();setTimeout(()=>{if(d.isConnected)d.remove()},4500)}
function setMode(mode){answerMode=mode;$('typeMode').classList.toggle('active',mode==='text');$('drawMode').classList.toggle('active',mode==='drawing');$('typePane').classList.toggle('hidden',mode!=='text');$('drawPane').classList.toggle('hidden',mode!=='drawing')}
$('typeMode').onclick=()=>setMode('text');$('drawMode').onclick=()=>setMode('drawing');
function pos(e){const r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)*canvas.width/r.width,y:(e.clientY-r.top)*canvas.height/r.height}}
canvas.addEventListener('pointerdown',e=>{if(canvas.dataset.locked==='1')return;e.preventDefault();canvas.setPointerCapture(e.pointerId);drawHistory.push(canvas.toDataURL('image/png'));if(drawHistory.length>8)drawHistory.shift();drawing=true;drawingDirty=true;const p=pos(e);ctx.beginPath();ctx.moveTo(p.x,p.y)});canvas.addEventListener('pointermove',e=>{if(!drawing)return;e.preventDefault();const p=pos(e);ctx.lineTo(p.x,p.y);ctx.stroke()});['pointerup','pointercancel','pointerleave'].forEach(ev=>canvas.addEventListener(ev,e=>{if(drawing){drawing=false;ctx.closePath()}}));
$('clearDraw').onclick=()=>{if(canvas.dataset.locked==='1')return;drawHistory.push(canvas.toDataURL('image/png'));resetCanvas()};$('undoDraw').onclick=()=>{if(canvas.dataset.locked==='1'||!drawHistory.length)return;const src=drawHistory.pop(),im=new Image();im.onload=()=>{ctx.drawImage(im,0,0);drawingDirty=true};im.src=src};
function currentKey(){return snap?.room?`${snap.room.round_no}-${snap.room.prompt_index}`:''}function syncClock(){if(snap?.server_now){serverBase=Date.parse(snap.server_now);perfBase=performance.now()}}function estimatedServerNow(){return serverBase+(performance.now()-perfBase)}function remainMs(){const d=snap?.room?.answer_deadline?Date.parse(snap.room.answer_deadline):0;return d?Math.max(0,d-estimatedServerNow()):0}function formatTimer(ms){const s=Math.ceil(ms/1000);return `${Math.floor(s/60)}:${String(s%60).padStart(2,'0')}`}
async function ensureDeadlineSubmission(){if(autoSubmitting||!session||!snap?.room||!['answering','final_answering'].includes(snap.room.status)||remainMs()>0||submittedKey===currentKey())return;autoSubmitting=true;try{const existing=await rpc('my_submission_snapshot',{p_room_id:session.room_id,p_player_id:session.player_id,p_player_token:session.player_token});if(existing){hydrateSubmission(existing,currentKey())}else await submitCurrent(true)}catch(e){toast(e.message)}finally{autoSubmitting=false}}
setInterval(()=>{if(currentScreen!=='answer'||!snap?.room)return;const ms=remainMs();$('timer').textContent=formatTimer(ms);$('timer').classList.toggle('urgent',ms<=10000);if(ms<=0)ensureDeadlineSubmission()},200);
function resetPromptUI(){submittedKey='';hydrateKey='';votedMatch='';finalVoted=false;roastShownKey='';$('answerText').value='';$('answerText').disabled=false;$('submitBtn').disabled=false;$('analysisBox').classList.add('hidden');$('analysisBox').innerHTML='';setMode('text');resetCanvas();canvas.dataset.locked='0'}
async function hydrateOwn(){const key=currentKey();if(!key||hydrateKey===key||submittedKey===key)return;hydrateKey=key;try{const s=await rpc('my_submission_snapshot',{p_room_id:session.room_id,p_player_id:session.player_id,p_player_token:session.player_token});if(s)hydrateSubmission(s,key)}catch(e){hydrateKey=''}}
function hydrateSubmission(s,key){submittedKey=key;$('answerText').disabled=true;$('submitBtn').disabled=true;canvas.dataset.locked='1';if(s.answer_type==='text'&&s.answer!=='[NO ANSWER]')$('answerText').value=s.answer;renderAnalysis(s.analysis||blankAnalysis(),key,true)}
async function createRoom(){const name=$('nick').value.trim();if(!name)return toast('Enter a nickname first.');const a=nameAnalyze(name);try{const d=await rpc('create_room',{p_name:name,p_name_raunch:a.score,p_name_bonus:0});session={...d,name,isHost:true,nameAnalysis:a};save();refresh(true)}catch(e){toast(e.message)}}
async function joinRoom(){const name=$('nick').value.trim(),code=$('joinCode').value.trim().toUpperCase();if(!name||code.length!==4)return toast('Enter a nickname and 4-character room code.');const a=nameAnalyze(name);try{const d=await rpc('join_room',{p_code:code,p_name:name,p_name_raunch:a.score,p_name_bonus:0});session={...d,name,isHost:false,nameAnalysis:a};save();refresh(true)}catch(e){toast(e.message)}}
async function refresh(force=false){if(!session)return;try{snap=await rpc('room_snapshot',{p_code:session.code});if(!snap?.room){leave('Game ended.');return}syncClock();render()}catch(e){if(force)toast(e.message)}}
function prepPrompt(r){const k=`${r.round_no}-${r.prompt_index}-${r.prompt_text}`;if(k!==lastPromptKey){lastPromptKey=k;resetPromptUI()}}
function render(){const r=snap.room,players=snap.players||[],me=players.find(x=>x.id===session.player_id);$('roomCode').textContent=r.code;document.querySelectorAll('.restart').forEach(b=>b.classList.toggle('hidden',!session.isHost));$('players').innerHTML=players.map(p=>`<div class="player"><span>${esc(p.name)} ${p.id===session.player_id?'(you)':''}</span><span class="small">READY</span></div>`).join('');if(r.status==='lobby'){show('lobby');$('lobbyStatus').textContent=`${players.length} player${players.length===1?'':'s'} joined.`;$('startBtn').classList.toggle('hidden',!session.isHost)}else if(r.status==='answering'||r.status==='final_answering'){show('answer');if(me)nameReveal(me);prepPrompt(r);$('roundLabel').innerHTML=r.status==='final_answering'?'<span class="finalTag">FINAL STRIPLASH · EVERYONE ANSWERS</span>':`ROUND ${r.round_no} · PROMPT ${r.prompt_index}/3`;$('prompt').textContent=r.prompt_text;$('timer').textContent=formatTimer(remainMs());const locked=submittedKey===currentKey();$('answerText').disabled=locked;$('submitBtn').disabled=locked;canvas.dataset.locked=locked?'1':'0';$('answerStatus').textContent=locked?`LOCKED IN — waiting for these slow bastards… ${snap.submitted}/${players.length}`:`${snap.submitted}/${players.length} answers submitted.`;const canVote=session.isHost&&snap.submitted>=2&&(snap.submitted>=players.length||remainMs()<=0);$('votingBtn').textContent=r.status==='final_answering'?'HOST: START FINAL VOTING':'HOST: START VOTING';$('votingBtn').classList.toggle('hidden',!canVote);hydrateOwn()}else if(r.status==='voting'){show('vote');$('votePrompt').textContent=r.prompt_text;loadMatchup()}else if(r.status==='results'){show('results');$('nextMatchBtn').classList.toggle('hidden',!session.isHost);$('waitNext').classList.toggle('hidden',session.isHost)}else if(r.status==='scores'){show('scores');const sorted=[...players].sort((a,b)=>b.score-a.score);$('leaderboard').innerHTML=sorted.map((p,i)=>`<div class="player"><span>${i+1}. <b>${esc(p.name)}</b></span><span><b>${p.score}</b> pts</span></div>`).join('');const finalReady=r.round_no===2&&r.prompt_index===3;$('nextPromptBtn').classList.toggle('hidden',!session.isHost||finalReady);$('startFinalBtn').classList.toggle('hidden',!session.isHost||!finalReady);$('scoreHeading').textContent=finalReady?'Round 2 Complete':'Leaderboard'}else if(r.status==='final_voting'){show('finalVote');loadFinal()}else if(r.status==='finished'){showWinner(players)}}
async function startGame(){try{await rpc('start_game',{p_room_id:session.room_id,p_host_token:session.host_token});nameRevealShown=false;refresh(true)}catch(e){toast(e.message)}}
function canvasData(){try{return canvas.toDataURL('image/webp',.58)}catch{return canvas.toDataURL('image/png')}}
async function submitCurrent(auto=false){if(!snap?.room)return;const key=currentKey();if(submittedKey===key)return;let typ=answerMode,ans=$('answerText').value.trim(),drawingData=null,a;if(typ==='drawing'){if(drawingDirty){drawingData=canvasData();a=blankAnalysis({drawing:true})}else{typ='no_answer';a=blankAnalysis({no_answer:true})}}else if(!ans){if(!auto)return toast('Type an answer, draw something, or wait for the timer.');typ='no_answer';a=blankAnalysis({no_answer:true})}else a=analyze(ans,snap.room.prompt_text);try{await rpc('submit_answer_v2',{p_room_id:session.room_id,p_player_id:session.player_id,p_player_token:session.player_token,p_answer_type:typ,p_answer:ans,p_drawing_data:drawingData,p_raunch:a.score||0,p_analysis:a});submittedKey=key;hydrateKey=key;$('answerText').disabled=true;$('submitBtn').disabled=true;canvas.dataset.locked='1';renderAnalysis(a,key,true);if(auto)toast(typ==='no_answer'?'TIME — no answer locked in.':'TIME — answer locked in.');refresh(true)}catch(e){toast(e.message)}}
$('submitBtn').onclick=()=>submitCurrent(false);
async function prepareVoting(){try{const fn=snap.room.status==='final_answering'?'prepare_final_voting':'prepare_voting';await rpc(fn,{p_room_id:session.room_id,p_host_token:session.host_token});refresh(true)}catch(e){toast(e.message)}}
function cardContent(type,answer,drawing){if(type==='drawing'&&drawing)return `<img src="${drawing}" alt="Player drawing">`;if(type==='no_answer')return `<div class="small">NO ANSWER</div>`;return `“${esc(answer)}”`}
async function loadMatchup(){try{const m=await rpc('active_matchup_snapshot',{p_code:session.code});if(!m)return;$('matchup').innerHTML=`<div class="answer">A: ${cardContent(m.a_type,m.a_answer,m.a_drawing)}<button onclick="castVote('${m.matchup_id}','${m.a_id}')">VOTE A</button></div><div class="answer">B: ${cardContent(m.b_type,m.b_answer,m.b_drawing)}<button onclick="castVote('${m.matchup_id}','${m.b_id}')">VOTE B</button></div>`;const v=+m.votes||0,e=+m.eligible_voters||0;$('voteStatus').innerHTML=session.isHost?`<b>${v}/${e}</b> players have voted.${e&&v>=e?' <b style="color:var(--green)">EVERYONE HAS VOTED ✓</b>':''}`:(votedMatch===m.matchup_id?'Vote locked in.':'Waiting for votes...');$('scoreBtn').classList.toggle('hidden',!session.isHost);$('scoreBtn').disabled=session.isHost&&e>0&&v<e}catch(e){toast(e.message)}}
window.castVote=async(mid,sid)=>{try{await rpc('cast_vote',{p_matchup_id:mid,p_player_id:session.player_id,p_player_token:session.player_token,p_submission_id:sid});votedMatch=mid;loadMatchup()}catch(e){toast(e.message)}};
async function scoreMatch(){try{await rpc('score_current_matchup',{p_room_id:session.room_id,p_host_token:session.host_token});refresh(true)}catch(e){toast(e.message)}}async function nextMatch(){try{await rpc('next_matchup',{p_room_id:session.room_id,p_host_token:session.host_token});votedMatch='';refresh(true)}catch(e){toast(e.message)}}async function nextPrompt(){try{await rpc('next_prompt',{p_room_id:session.room_id,p_host_token:session.host_token});refresh(true)}catch(e){toast(e.message)}}async function startFinal(){try{await rpc('start_final_round',{p_room_id:session.room_id,p_host_token:session.host_token});refresh(true)}catch(e){toast(e.message)}}
async function loadFinal(){try{const f=await rpc('final_round_snapshot',{p_code:session.code});$('finalPrompt').textContent=f.room.prompt_text;const answers=f.answers||[];$('finalAnswers').innerHTML=answers.map((a,i)=>`<div class="answer">${i+1}. ${cardContent(a.answer_type,a.answer,a.drawing_data)}${a.player_id===session.player_id?'<div class="small">YOUR ANSWER</div>':`<button onclick="castFinal('${a.submission_id}')">VOTE FOR THIS</button>`}</div>`).join('');const v=+f.votes_cast||0,e=+f.eligible_voters||0;$('finalVoteStatus').innerHTML=session.isHost?`<b>${v}/${e}</b> players have voted.${e&&v>=e?' <b style="color:var(--green)">EVERYONE HAS VOTED ✓</b>':''}`:(finalVoted?'Final vote locked in.':'Choose your favorite answer.');$('scoreFinalBtn').classList.toggle('hidden',!session.isHost);$('scoreFinalBtn').disabled=session.isHost&&v<e}catch(e){toast(e.message)}}
window.castFinal=async sid=>{try{await rpc('cast_final_vote',{p_room_id:session.room_id,p_player_id:session.player_id,p_player_token:session.player_token,p_submission_id:sid});finalVoted=true;toast('Final vote locked in');loadFinal()}catch(e){toast(e.message)}};async function scoreFinal(){try{await rpc('score_final_round',{p_room_id:session.room_id,p_host_token:session.host_token});refresh(true)}catch(e){toast(e.message)}}
function confetti(){for(let i=0;i<70;i++){const d=document.createElement('i');d.className='confetti';d.style.left=Math.random()*100+'vw';d.style.animationDelay=Math.random()*1.2+'s';d.style.background=`hsl(${Math.random()*360} 90% 60%)`;document.body.appendChild(d);setTimeout(()=>d.remove(),4700)}}
function showWinner(players){show('winner');const sorted=[...players].sort((a,b)=>b.score-a.score),w=sorted[0];$('winnerName').textContent=w?.name||'Winner';$('winnerScore').textContent=(w?.score||0)+' PTS';$('finalLeaderboard').innerHTML=sorted.map((p,i)=>`<div class="player"><span>${i+1}. <b>${esc(p.name)}</b></span><b>${p.score}</b></div>`).join('');document.querySelector('#winner .restart').classList.toggle('hidden',!session.isHost);if(!winnerShown){winnerShown=true;confetti()}}
async function restartGame(){if(!session?.isHost)return;if(!confirm('Restart the game? Everyone will be kicked back to the main screen.'))return;try{await rpc('restart_game',{p_room_id:session.room_id,p_host_token:session.host_token});leave('Game restarted.')}catch(e){toast(e.message)}}
$('createBtn').onclick=createRoom;$('joinBtn').onclick=joinRoom;$('leaveBtn').onclick=()=>leave();$('startBtn').onclick=startGame;$('votingBtn').onclick=prepareVoting;$('scoreBtn').onclick=scoreMatch;$('nextMatchBtn').onclick=nextMatch;$('nextPromptBtn').onclick=nextPrompt;$('startFinalBtn').onclick=startFinal;$('scoreFinalBtn').onclick=scoreFinal;document.querySelectorAll('.restart').forEach(b=>b.onclick=restartGame);if(session){$('nick').value=session.name||'';refresh(true)}else show('home');setInterval(()=>{if(session)refresh(false)},1000);